# Generated by Django 2.2.7 on 2020-01-18 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=20)),
                ('desc', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'category',
            },
        ),
    ]
